### ISSUE TITLE
AssetHat::CONFIG_FILEPATH inconsistencies

### ISSUE THREAD

**Issue by kainosnoema** [mintdigital/asset_hat#1]
When running the asset_hat:config task, I'm getting "No such file or directory" errors. The path in the error is similar to:

```
/[ path to app root ]/[ path to app root AGAIN ]/config/assets.yml
```

Looking around, I found that AssetHat::CONFIG_FILEPATH is defined to be the absolute path to the config file in RAILS_ROOT:

```
CONFIG_FILEPATH = File.join(RAILS_ROOT, 'config', 'assets.yml')
```

But then, in asset_hat/tasks.rb (asset_hat:config), the target file path is defined as RAILS_ROOT joined with AssetHat::CONFIG_FILEPATH. Thus the RAILS_ROOT is being appended twice:

```
target_filepath = File.join(RAILS_ROOT, AssetHat::CONFIG_FILEPATH)
```

**Comment by rondevera** [comment]
Thanks for reporting this! I've pushed version 0.1.4 to RubyGems.org to patch this.

Sorry I didn't see this ticket sooner. If GitHub sent an email notification, it may have gone to a shared account that I don't monitor.
