### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by krist0ff** [mintdigital/asset_hat#2]
Asset Hat should us https:// urls for hosted Javascript when we're serving the page over https.
Otherwise browser complains about non-secure elements. Not sure if all external resources that are means to be used by asset hat have https version, but I'm sure google stuff does

**Comment by krist0ff** [comment]
btw we are using 0.1.5 but I haven't sen anything later that would fix the issue

**Comment by rondevera** [comment]
Covered in v0.3.0 release. Please let me know if you have any more problems. Thanks!
