### ISSUE TITLE
unitialized constant Rails::Plugin::AssetHatHelper  (Rails 2.2.2)

### ISSUE THREAD

**Issue by barmstrong** [mintdigital/asset_hat#4]
Anyone got this working with Rails 2.2.2 ?

I get unitialized constant Rails::Plugin::AssetHatHelper

```
uninitialized constant Rails::Plugin::AssetHatHelper
/Users/barmstrong/NetBeansProjects/viper/vendor/rails/activesupport/lib/active_support/dependencies.rb:102:in `const_missing'
/Users/barmstrong/NetBeansProjects/viper/vendor/gems/asset_hat-0.3.0/rails/init.rb:1:in `evaluate_init_rb'
```

**Comment by rondevera** [comment]
Thanks for reporting this. Which versions of Ruby and RubyGems are you using? Is there any difference if you activate the gem via `config.gem` (or [Bundler](http://gembundler.com/), if you have it working with Rails 2.2.x) instead of `/vendor/gems/`?

**Comment by barmstrong** [comment]
Hi rondevera,

Thanks for the response!

```
barmstrong:~$ gem -v
1.3.7
barmstrong:~$ ruby -v
ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]
```

Tried it with config.gem and got similar result.  Unfortunately not using Bundler (it's an older rails project).  I don't have a great understanding of how gems get loaded in different versions of rails, but it seems like it could be something fairly simple.

**Comment by rondevera** [comment]
v0.4 is available now, and it adds support for Rails 3. Unfortunately, this meant dropping Rails 2.2 support in favor of moving forward.
